#!/bin/bash

myCurrentDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
: ${psDir:=$myCurrentDIR} ; export psDir
. `dirname "${BASH_SOURCE[0]}"`/bashrc

if [ -n "$1" ]; then 
	dataFiles=$1
else
	dataFiles="$(ls )"
fi
	







for case in $dataFiles
do
	if [ -f $case/Makefile ]; then
		echo "$case:"	
		(cd $case && make clean)
	elif [ -f $case/makefile ]; then
		echo "$case:"	
		(cd $case && make clean)
	else 
		if [ -d $case ]; then
			echo " skipping $case"	
		fi
	fi
done


