#!/bin/bash

SetedpsDir="$psDir"

myUpperDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
myCurrentDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
if ! [ -n "$psDir" ]; then
	echo " ";	echo " psDir variable is not set" ; echo " "
	source $myCurrentDIR/bashrc
	echo " Press Ctrl+C to stop ";	echo " ";
	sleep 3
else
	source $myCurrentDIR/bashrc
fi

if ! [ -f $WM_PROJECT_DIR/etc/bashrc ]; then
	echo "Error: "
	echo " OpenFOAM installation directory is not set."
	echo " Please set it in the file: $psDir/porefoam/bashrc"
	echo " and try again"
	exit
fi



if ! [ -d $myOFBinDir ]; then
    mkdir -p $myOFBinDir
fi



if [ -n "$1" ]; then
    targets=$1
else
	targets="$(ls -d */ )"
fi



for case in $targets ; do
  if [ -f $case/makefile ]; then 
	 echo ;  echo "* cd $case && make:"
	 (cd $case && make)
  fi
done
for case in $targets ; do
  if [ -f $case/Makefile ]; then 
	 echo ;  echo "* cd $case && make:"
	 (cd $case && make ) &
  fi
done



echo "build directory: $myOFBinDir"
if ! [ -n "$SetedpsDir" ]; then
	echo " ";	echo " ";
	echo " variable psDir is not permanently set"
	echo " please set in your ~/.bashrc file by adding new line:"
	echo "source $myUpperDIR/bashrc"
	echo " ";
	sleep 1
fi
