#!/bin/bash


myUpperDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )


# openfoam installation
# Change according to your openfoam installation directory
#export WM_NCOMPPROCS=28
export FOAM_INST_DIR=$myUpperDIR/../thirdparty
source $FOAM_INST_DIR/foam-miniext-3.4/etc/bashrc



if ! [ -n "$psDir" ]; then
	echo " Openfoam dir: $WM_PROJECT_DIR"
	echo ; echo " Hint: to permanently install, add the following to your ~/.bashrc file:"
	echo "  source $myUpperDIR/bashrc" ; echo
	source $myUpperDIR/bashrc
fi

export myOFBinDir=$psBinDir/porefoam-ext-3.4

export PATH=$PATH:$myOFBinDir
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$myOFBinDir

export FOAM_ABORT=1
