name: build and release

on:
  push:
    tags: 
      - "v*.*.*"
    branches:
      - "master"
    paths:
      - "src/**"
      - "thirdparty/**"
      - "Dockerfile"
      - "Makefile"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_publish:
    name: Build and publish to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/porefoam

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/porefoam:latest
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker, dest=/tmp/myimage.tar
      
      - name: publish to docker hub
        run: |
          docker load --input /tmp/myimage.tar
          docker push ${{ secrets.DOCKER_USERNAME }}/porefoam:latest

      - name: create container
        run: |
          docker create --name porefoam ${{ secrets.DOCKER_USERNAME }}/porefoam:latest
      
      - name: extract binary from container
        run: |
          docker cp porefoam:/home/foam/porefoam/ ./out/
      
      - name: Archive files
        run: |
          7z a -tzip porefoam.zip ./out/**
      
      - name: uploads artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: porefoam.zip

  release:
    name: release binary to release page
    needs: build_and_publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4 

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: binary
          path: /tmp

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/porefoam.zip